# -*- coding: utf-8 -*-
"""MosquitoData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17qXWB4T9bgiqP_Sj6YMU4_aaaca1_8O3
"""

